# Generated by Django 4.1.13 on 2024-09-03 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="created_in",
        ),
        migrations.RemoveField(
            model_name="class",
            name="image",
        ),
        migrations.AddField(
            model_name="domain",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="domain_images/"),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="class",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="item.domain",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="item.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("image", "Image"),
                            ("excel", "Excel File"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="resources/")),
                (
                    "class_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="item.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to="item.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="excel_files/")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="excel_images/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_files",
                        to="item.domain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="learning_paths",
            field=models.ManyToManyField(
                blank=True, related_name="classes", to="item.learningpath"
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.class"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
    ]
