# Generated by Django 4.1.13 on 2024-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_remove_class_created_in_remove_class_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
    ]
