# Generated by Django 4.1.13 on 2024-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_remove_enrollment_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                    ("ended", "Ended"),
                ],
                default="ongoing",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
