# Generated by Django 4.1.13 on 2024-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_enrollment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                    ("ended", "Ended"),
                ],
                default="ongoing",
                max_length=20,
            ),
        ),
    ]
